version: "3.4"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - internal
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  phraseanet:
    build:
      target: phraseanet_debug
    environment:
      - DOCKER_XDEBUG_ENABLED
      - PHP_IDE_CONFIG=serverName=${SERVER_NAME}

  dev:
    build:
      context: dev
    networks:
      - internal
    stdin_open: true
    tty: true
    hostname: local
    environment:
      - SYMFONY_ENV
      - SSH_AUTH_SOCK=/ssh-auth-sock
      - DOCKER_XDEBUG_ENABLED
      - PHP_IDE_CONFIG=serverName=${SERVER_NAME}
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
      - phraseanet
    volumes:
      - alchemy_vol:/var/alchemy
      - data_vol:/var/data
      - dev_vol:/home/app
      - ~/.ssh:/home/app/.ssh

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
