version: "3.4"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  db:
    build: ./db

  gateway:
    volumes:
        - alchemy_vol:/var/alchemy

  phraseanet:
    #build:
      #target: phraseanet_debug
    #environment:
      #- DOCKER_XDEBUG_ENABLED
      #- PHP_IDE_CONFIG=serverName=${SERVER_NAME}
    volumes:
      - alchemy_vol:/var/alchemy

  worker:
    volumes:
      - alchemy_vol:/var/alchemy

  dev:
    build:
      context: dev
    stdin_open: true
    tty: true
    hostname: local
    environment:
      - SYMFONY_ENV
      - SSH_AUTH_SOCK=/ssh-auth-sock
      - DOCKER_XDEBUG_ENABLED
      - PHP_IDE_CONFIG=serverName=${SERVER_NAME}
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
      - phraseanet
    volumes:
      - alchemy_vol:/var/alchemy
      - data_vol:/var/data
      - dev_vol:/home/app
      - ~/.ssh:/home/app/.ssh

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

volumes:
  alchemy_vol:
    driver: local
    driver_opts:
      type: none
      device: ${ALCHEMY_WORKSPACE_DIR}
      o: bind
