version: "3.4"

networks:
  internal:

services:
  nginx:
    build:
      context: nginx
    networks:
      - internal
    restart: always
    volumes:
        - alchemy_vol:/var/alchemy
        - data_vol:/var/data
    depends_on:
      - phraseanet
    ports:
      - ${PHRASEANET_APP_PORT}:80

  phraseanet:
    build:
      context: phraseanet
      target: phraseanet_prod
    image: phraseanet
    networks:
      - internal
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    volumes:
      - alchemy_vol:/var/alchemy
      - data_vol:/var/data

  worker:
    build:
      context: worker
    networks:
      - internal
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    volumes:
      - alchemy_vol:/var/alchemy
      - data_vol:/var/data

  db:
    build:
      context: db
    networks:
      - internal
    command: mysqld --sql_mode=""
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
     - db_vol:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - internal
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  redis:
    image: redis
    networks:
      - internal

  elasticsearch:
    build: elasticsearch
    networks:
      - internal
    restart: always
    volumes:
      - elasticsearch_vol:/usr/share/elasticsearch/data

volumes:
  alchemy_vol:
    driver: local
    driver_opts:
      type: none
      device: ${ALCHEMY_WORKSPACE_DIR}
      o: bind
  data_vol:
    driver: local
  db_vol:
    driver: local
  elasticsearch_vol:
    driver: local
  dev_vol:
    driver: local
